const SET_GLOBAL_LOADING = 'SET_GLOBAL_LOADING';

const API_GET_HEALTH_CHECK = 'API_GET_HEALTH_CHECK';
const API_SET_HEALTH_INFO = 'API_SET_HEALTH_INFO';

export const ACTIONS = {
  SET_GLOBAL_LOADING,

  API_GET_HEALTH_CHECK,
  API_SET_HEALTH_INFO,
};

export default ACTIONS;
